sudo: true
language: python
python:
  - "2.7"
branches:
  only:
    - indigo
    - jade
env:
  global:
    - REPO: github.com/otamachan/sphinxros.git
    - ROSDISTRO: ${TRAVIS_BRANCH}
    - DEBS_PATH: debs
    - secure: "NePXFdCHZ79wa+sN43nWhRbHT8VfDWL0a4vjPKGiNFUK67xdYRMa0+BWBoSXhUEy35UluonmolHUHQnoxL9603KZ8nnWjnFh4tuMvOuNmhcQz45+Ln6BLDTPrJBy2k8483aHHH0cGfsqK9MgJC5euzGrPE7+N9DKwRrB5SYInZDhEj6q23h6fzbarbJ3pM5KH7AuxBrXiqOiEbDDoHaIuGdGdIvM3ua/nYwZcMZurq9wj17XZ+3htfdLeRQIjjGQPj6Y/9vTayDuY9QafoYHEcM0Be5c8beFOp0UyzDTxKsdUB0Glr+IeW7zq8/uFi9x8UihpO6LwWeNyMoOr36Q2JU/y1WLlSOZMp2oNOm8qjn8rCzJvdqanONDf0gnJ3aSjPSH11xRD2AK73UbFB56rcaTQmnYbY21PRhllbsdmj6OLhnv3HmYRB9gP6Wj4VtCxpz8dMUNq4h/kwl0R9iPVUl1NNSsHzMAKS4Rz6wYc197w9kLwl+5vB+v8Pi+bQ9VHqTYuSE9k8RjCiBe8cuXaJbA9aSgxrPSehVgK1oU6dkeTlWWa5A6xz4Jq77UqH38Go0e418fjBdDLdvwFfCnzUj2KU7WoQafIu9qm9Mlm3wsI+MGF1RcEe7NumVf5F1zVaFq4Enkxu3oHtNO9ZnNc6/DjWXU9iGDGhiDqTD7Cek="
services:
  - docker
before_install:
  - mkdir ${DEBS_PATH}
  - git clone --depth=1 --branch=master "https://${REPO}" master
  - docker run -v `pwd`:/workspace -e "ROSDISTRO=${ROSDISTRO}" ros:${ROSDISTRO}-ros-core /workspace/master/scripts/get_debs.sh /workspace/${DEBS_PATH}
install:
  - pip install -r ./master/requirements.txt
  - pip install git+https://github.com/otamachan/sphinxcontrib-ros.git
  - for deb in $(find ${DEBS_PATH} -iname '*.deb' | sort); do echo $deb; sudo dpkg --force-all -i $deb > /dev/null 2&>1; done; true
  # clone
  - git clone --depth=1 --branch=gh-pages "https://${REPO}" _build
  - ln -s packages ./master/doc/packages
  # generate docs
  - ./master/scripts/generator.py $ROSDISTRO ./master/doc/packages
  - rm _build/.git _build/$ROSDISTRO -rf
script:
  - echo Building $(ls -1 ./master/doc/packages/*.rst | wc -l) packages
  - sphinx-build -a -E -b html -d /tmp ./master/doc _build/$ROSDISTRO
after_success:
  # push
  - git -C _build init
  - git -C _build config user.name "Travis CI"
  - git -C _build config user.email "otamachan@gmail.com"
  - git -C _build add --all .
  - git -C _build commit --quiet -m "Deploy to GitHub Pages"
  - git -C _build push --force --quiet "https://${GH_TOKEN}@${REPO}" master:gh-pages> /dev/null 2>&1
